# version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # React
      - "5000:5000" # Flask
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      NODE_ENV: development
    command: npm start
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json
